### PR TITLE
Introduce UI.title property

### PR DESCRIPTION
**Pull request by ro0gr**
Related comment: https://github.com/ember-cli/ember-cli/pull/6468#issuecomment-263079185

Also extended `MockUI` to have a process mock by default.

_Maybe it's an obvious point but I think it's better not to merge this till we have some pull request with working integration in ember-cli._

### CODE REVIEW

**Comment by stefanpenner** [comment]
@ro0gr regardless of what we do in ember-cli, I think this is totally a good addition here. We can always update it, as we learn more.

Can up also update the readme?

**Comment by ro0gr** [comment]
> Im actually somewhat unsure about changing the process.title to drastically we do want it to show up reasonable in ps / htop etc and work with killall -9 ember

@stefanpenner this comment makes me think that we'd better not touch `process.title` at all. 
Do you think it still has legitimate use cases? I'm in big doubts here.

**Comment by ro0gr** [comment]
Anyway if you think it has reasons to live I'll gladly update the readme

**Comment by stefanpenner** [comment]
@ro0gr ya, although I am unsure about that use-case. I do believe interacting with `process.title` via this facade would have been good for ember-cli originally (especially for testing) Although it may be tricky to use this i ember-cli, it still feels right. Thoughts?

**Comment by ro0gr** [comment]
> interacting with process.title via this facade would have been good for ember-cli originally (especially for testing)

Yes, there are possible benefits for testing. But as I can see right now `ember-cli` uses `process.title` only once. This code path is not very testable by its nature. 
So I don't think we can have any immediate benefit from this feature because "nobody needs it" :slightly_smiling_face:

**Comment by ro0gr** [comment]
I think we can close it for now. If we find a real use case for this we can always restore it.

**Pull request closed without merging**
